// GENERATED by scripts/gen-mcp-actions.mjs — do not edit by hand.
/* eslint-disable */
import type { ZodTypeAny } from "zod";
import * as m0 from "@/actions/activity/activities";
import * as m1 from "@/actions/activity/activityTypes";
import * as m2 from "@/actions/activity/breaks";
import * as m3 from "@/actions/activity/timer";
import * as m4 from "@/actions/agentChat.actions";
import * as m5 from "@/actions/apiKey.actions";
import * as m6 from "@/actions/atsCompany.actions";
import * as m7 from "@/actions/automation/analyze";
import * as m8 from "@/actions/automation/discoveredJobs";
import * as m9 from "@/actions/automation/mutations";
import * as m10 from "@/actions/automation/queries";
import * as m11 from "@/actions/automation/runs";
import * as m12 from "@/actions/company/mutations";
import * as m13 from "@/actions/company/queries";
import * as m14 from "@/actions/company/watch";
import * as m15 from "@/actions/contact/jobLinks";
import * as m16 from "@/actions/contact/mutations";
import * as m17 from "@/actions/contact/queries";
import * as m18 from "@/actions/contactRole.actions";
import * as m19 from "@/actions/coverLetter.actions";
import * as m20 from "@/actions/job/mutations";
import * as m21 from "@/actions/job/queries";
import * as m22 from "@/actions/job/references";
import * as m23 from "@/actions/job/status";
import * as m24 from "@/actions/jobLocation.actions";
import * as m25 from "@/actions/jobSource.actions";
import * as m26 from "@/actions/jobtitle.actions";
import * as m27 from "@/actions/mcpToken.actions";
import * as m28 from "@/actions/note.actions";
import * as m29 from "@/actions/profile/certification";
import * as m30 from "@/actions/profile/contactInfo";
import * as m31 from "@/actions/profile/defaultResume";
import * as m32 from "@/actions/profile/education";
import * as m33 from "@/actions/profile/experience";
import * as m34 from "@/actions/profile/files";
import * as m35 from "@/actions/profile/resume";
import * as m36 from "@/actions/profile/resumeCopy";
import * as m37 from "@/actions/profile/skills";
import * as m38 from "@/actions/profile/summary";
import * as m39 from "@/actions/question.actions";
import * as m40 from "@/actions/resumeImport.actions";
import * as m41 from "@/actions/tag.actions";
import * as m42 from "@/actions/task/activity";
import * as m43 from "@/actions/task/mutations";
import * as m44 from "@/actions/task/queries";
import * as m45 from "@/actions/userSettings.actions";
import { AddCompanyFormSchema } from "@/models/addCompanyForm.schema";
import { AddJobFormSchema } from "@/models/addJobForm.schema";
import { NoteFormSchema } from "@/models/note.schema";
import { AddCertificationFormSchema } from "@/models/addCertificationForm.schema";
import { AddContactInfoFormSchema } from "@/models/addContactInfoForm.schema";
import { AddEducationFormSchema } from "@/models/AddEductionForm.schema";
import { AddExperienceFormSchema } from "@/models/addExperienceForm.schema";
import { AddSkillsFormSchema, UpdateSkillsFormSchema } from "@/models/skills.schema";
import { AddSummarySectionFormSchema } from "@/models/addSummaryForm.schema";
import { AddQuestionFormSchema } from "@/models/addQuestionForm.schema";
import { AddTaskFormSchema } from "@/models/addTaskForm.schema";

export interface McpActionEntry {
  fn: (...args: any[]) => Promise<unknown> | unknown;
  signature: string;
  params: { name: string; type: string; optional: boolean }[];
  doc: string;
  schemas: Record<string, ZodTypeAny>;
}

export const MCP_ACTIONS: Record<string, McpActionEntry> = {
  "activity.getActivitiesList": { fn: m0.getActivitiesList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, search?: string", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"search","type":"string","optional":true}], doc: "", schemas: {  } },
  "activity.createActivity": { fn: m0.createActivity as any, signature: "data: Activity", params: [{"name":"data","type":"Activity","optional":false}], doc: "", schemas: {  } },
  "activity.deleteActivityById": { fn: m0.deleteActivityById as any, signature: "activityId: string", params: [{"name":"activityId","type":"string","optional":false}], doc: "", schemas: {  } },
  "activity.getAllActivityTypes": { fn: m1.getAllActivityTypes as any, signature: "", params: [], doc: "", schemas: {  } },
  "activity.createActivityType": { fn: m1.createActivityType as any, signature: "label: string", params: [{"name":"label","type":"string","optional":false}], doc: "", schemas: {  } },
  "activity.getActivityTypeList": { fn: m1.getActivityTypeList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE,", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true}], doc: "", schemas: {  } },
  "activity.deleteActivityTypeById": { fn: m1.deleteActivityTypeById as any, signature: "activityTypeId: string,", params: [{"name":"activityTypeId","type":"string","optional":false}], doc: "", schemas: {  } },
  "activity.startBreak": { fn: m2.startBreak as any, signature: "activityId: string, plannedMinutes: number,", params: [{"name":"activityId","type":"string","optional":false},{"name":"plannedMinutes","type":"number","optional":false}], doc: "", schemas: {  } },
  "activity.endBreak": { fn: m2.endBreak as any, signature: "activityId: string,", params: [{"name":"activityId","type":"string","optional":false}], doc: "", schemas: {  } },
  "activity.updateBreakLength": { fn: m2.updateBreakLength as any, signature: "activityId: string, plannedMinutes: number,", params: [{"name":"activityId","type":"string","optional":false},{"name":"plannedMinutes","type":"number","optional":false}], doc: "", schemas: {  } },
  "activity.startActivityById": { fn: m3.startActivityById as any, signature: "activityId: string", params: [{"name":"activityId","type":"string","optional":false}], doc: "", schemas: {  } },
  "activity.stopActivityById": { fn: m3.stopActivityById as any, signature: "activityId: string, endTime: Date,", params: [{"name":"activityId","type":"string","optional":false},{"name":"endTime","type":"Date","optional":false}], doc: "", schemas: {  } },
  "activity.getCurrentActivity": { fn: m3.getCurrentActivity as any, signature: "", params: [], doc: "", schemas: {  } },
  "agentChat.getChatConversation": { fn: m4.getChatConversation as any, signature: "", params: [], doc: "", schemas: {  } },
  "agentChat.saveChatConversation": { fn: m4.saveChatConversation as any, signature: "messages: UIMessage[],", params: [{"name":"messages","type":"UIMessage[]","optional":false}], doc: "", schemas: {  } },
  "agentChat.clearChatConversation": { fn: m4.clearChatConversation as any, signature: "", params: [], doc: "", schemas: {  } },
  "apiKey.getUserApiKeys": { fn: m5.getUserApiKeys as any, signature: "", params: [], doc: "", schemas: {  } },
  "apiKey.saveApiKey": { fn: m5.saveApiKey as any, signature: "input: { provider: string; key: string; label?: string; sensitive?: boolean; }", params: [{"name":"input","type":"{ provider: string; key: string; label?: string; sensitive?: boolean; }","optional":false}], doc: "", schemas: {  } },
  "apiKey.deleteApiKey": { fn: m5.deleteApiKey as any, signature: "provider: string", params: [{"name":"provider","type":"string","optional":false}], doc: "", schemas: {  } },
  "apiKey.getDefaultOllamaBaseUrl": { fn: m5.getDefaultOllamaBaseUrl as any, signature: "", params: [], doc: "", schemas: {  } },
  "atsCompany.searchAtsCompanies": { fn: m6.searchAtsCompanies as any, signature: "provider: JobBoard, query: string, offset = 0,", params: [{"name":"provider","type":"JobBoard","optional":false},{"name":"query","type":"string","optional":false},{"name":"offset","type":"unknown","optional":true}], doc: "Typeahead over the seeded companies.json (server-side filter, paginated). An empty query browses the full list (alphabetical); `offset` drives the infinite-scroll load-more. Returns a page plus whether more remain.", schemas: {  } },
  "atsCompany.getAtsCompanyCount": { fn: m6.getAtsCompanyCount as any, signature: "provider: JobBoard", params: [{"name":"provider","type":"JobBoard","optional":false}], doc: "Total number of companies in the seeded directory (for a browse hint).", schemas: {  } },
  "atsCompany.resolveAtsBoard": { fn: m6.resolveAtsBoard as any, signature: "provider: JobBoard, input: string,", params: [{"name":"provider","type":"JobBoard","optional":false},{"name":"input","type":"string","optional":false}], doc: "Validate a token or board URL; returns the display company name (and, for Lever, the resolved host). Dispatches per provider.", schemas: {  } },
  "automation.analyzeDiscoveredJob": { fn: m7.analyzeDiscoveredJob as any, signature: "jobId: string", params: [{"name":"jobId","type":"string","optional":false}], doc: "Runs an on-demand LLM match for an un-analyzed discovered job using the resume tied to its automation and the user's AI settings (no model picker — mirrors the automation runner). Upgrades matchData with analyzed: true.", schemas: {  } },
  "automation.getDiscoveredJobs": { fn: m8.getDiscoveredJobs as any, signature: "options?: { automationId?: string; discoveryStatus?: DiscoveryStatus | DiscoveryStatus[]; page?: number; limit?: number; sortBy?: \"matchScore\" | \"discoveredAt\"; sortOrder?: \"asc\" | \"desc\"; }", params: [{"name":"options","type":"{ automationId?: string; discoveryStatus?: DiscoveryStatus | DiscoveryStatus[]; page?: number; limit?: number; sortBy?: \"matchScore\" | \"discoveredAt\"; sortOrder?: \"asc\" | \"desc\"; }","optional":true}], doc: "", schemas: {  } },
  "automation.getDiscoveredJobById": { fn: m8.getDiscoveredJobById as any, signature: "id: string", params: [{"name":"id","type":"string","optional":false}], doc: "", schemas: {  } },
  "automation.dismissDiscoveredJob": { fn: m8.dismissDiscoveredJob as any, signature: "id: string", params: [{"name":"id","type":"string","optional":false}], doc: "", schemas: {  } },
  "automation.clearDiscoveredJobs": { fn: m8.clearDiscoveredJobs as any, signature: "options: { automationId: string; includeNew?: boolean; }", params: [{"name":"options","type":"{ automationId: string; includeNew?: boolean; }","optional":false}], doc: "Bulk-deletes discovered jobs for one automation. Always keeps accepted jobs (they're tracked) and deletes dismissed ones; includeNew also clears the unreviewed \"new\" pile.", schemas: {  } },
  "automation.acceptDiscoveredJob": { fn: m8.acceptDiscoveredJob as any, signature: "id: string", params: [{"name":"id","type":"string","optional":false}], doc: "", schemas: {  } },
  "automation.createAutomation": { fn: m9.createAutomation as any, signature: "input: CreateAutomationInput", params: [{"name":"input","type":"CreateAutomationInput","optional":false}], doc: "", schemas: {  } },
  "automation.updateAutomation": { fn: m9.updateAutomation as any, signature: "id: string, input: UpdateAutomationInput,", params: [{"name":"id","type":"string","optional":false},{"name":"input","type":"UpdateAutomationInput","optional":false}], doc: "", schemas: {  } },
  "automation.deleteAutomation": { fn: m9.deleteAutomation as any, signature: "id: string", params: [{"name":"id","type":"string","optional":false}], doc: "", schemas: {  } },
  "automation.pauseAutomation": { fn: m9.pauseAutomation as any, signature: "id: string", params: [{"name":"id","type":"string","optional":false}], doc: "", schemas: {  } },
  "automation.resumeAutomation": { fn: m9.resumeAutomation as any, signature: "id: string", params: [{"name":"id","type":"string","optional":false}], doc: "", schemas: {  } },
  "automation.getAutomationsList": { fn: m10.getAutomationsList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE,", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true}], doc: "", schemas: {  } },
  "automation.getAutomationById": { fn: m10.getAutomationById as any, signature: "id: string", params: [{"name":"id","type":"string","optional":false}], doc: "", schemas: {  } },
  "automation.getAutomationRuns": { fn: m11.getAutomationRuns as any, signature: "automationId: string, options?: { page?: number; limit?: number; },", params: [{"name":"automationId","type":"string","optional":false},{"name":"options","type":"{ page?: number; limit?: number; }","optional":true}], doc: "", schemas: {  } },
  "automation.deleteAutomationRun": { fn: m11.deleteAutomationRun as any, signature: "runId: string,", params: [{"name":"runId","type":"string","optional":false}], doc: "", schemas: {  } },
  "company.addCompany": { fn: m12.addCompany as any, signature: "data: z.infer<typeof AddCompanyFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddCompanyFormSchema>","optional":false}], doc: "", schemas: { AddCompanyFormSchema } },
  "company.updateCompany": { fn: m12.updateCompany as any, signature: "data: z.infer<typeof AddCompanyFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddCompanyFormSchema>","optional":false}], doc: "", schemas: { AddCompanyFormSchema } },
  "company.deleteCompanyById": { fn: m12.deleteCompanyById as any, signature: "companyId: string,", params: [{"name":"companyId","type":"string","optional":false}], doc: "", schemas: {  } },
  "company.getCompanyList": { fn: m13.getCompanyList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, countBy?: string, search?: string, scope: \"mine\" | \"watchlist\" = \"mine\",", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"countBy","type":"string","optional":true},{"name":"search","type":"string","optional":true},{"name":"scope","type":"\"mine\" | \"watchlist\"","optional":true}], doc: "", schemas: {  } },
  "company.getAllCompanies": { fn: m13.getAllCompanies as any, signature: "", params: [], doc: "", schemas: {  } },
  "company.getCompanyById": { fn: m13.getCompanyById as any, signature: "companyId: string,", params: [{"name":"companyId","type":"string","optional":false}], doc: "", schemas: {  } },
  "company.getCompanyDetails": { fn: m13.getCompanyDetails as any, signature: "companyId: string,", params: [{"name":"companyId","type":"string","optional":false}], doc: "null covers both a missing id and another user's company, so the page's 404 never reveals which. Dismissed jobs are hidden like on the Jobs page, but counted, because deleteCompanyById's job guard still sees them.", schemas: {  } },
  "company.watchBoardCompany": { fn: m14.watchBoardCompany as any, signature: "provider: JobBoard, board: { name: string; token: string; host?: LeverHost }, opts?: { confirmMerge?: boolean },", params: [{"name":"provider","type":"JobBoard","optional":false},{"name":"board","type":"{ name: string; token: string; host?: LeverHost }","optional":false},{"name":"opts","type":"{ confirmMerge?: boolean }","optional":true}], doc: "Watches a board from the seed directory. Makes no network call: the name, token and host all arrive from JSON the browse view already loaded.", schemas: {  } },
  "company.setCompanyWatched": { fn: m14.setCompanyWatched as any, signature: "companyId: string, watched: boolean,", params: [{"name":"companyId","type":"string","optional":false},{"name":"watched","type":"boolean","optional":false}], doc: "Toggles watch intent only. Board coordinates stay true after unwatching, so re-watching is one click; removing the row entirely is deleteCompanyById.", schemas: {  } },
  "company.getWatchedBoards": { fn: m14.getWatchedBoards as any, signature: "provider?: JobBoard,", params: [{"name":"provider","type":"JobBoard","optional":true}], doc: "", schemas: {  } },
  "contact.getJobContacts": { fn: m15.getJobContacts as any, signature: "jobId: string,", params: [{"name":"jobId","type":"string","optional":false}], doc: "", schemas: {  } },
  "contact.addJobContact": { fn: m15.addJobContact as any, signature: "jobId: string, contactId: string, roleId: string,", params: [{"name":"jobId","type":"string","optional":false},{"name":"contactId","type":"string","optional":false},{"name":"roleId","type":"string","optional":false}], doc: "", schemas: {  } },
  "contact.removeJobContact": { fn: m15.removeJobContact as any, signature: "linkId: string,", params: [{"name":"linkId","type":"string","optional":false}], doc: "", schemas: {  } },
  "contact.createContact": { fn: m16.createContact as any, signature: "values: ContactFormValues,", params: [{"name":"values","type":"ContactFormValues","optional":false}], doc: "", schemas: {  } },
  "contact.updateContact": { fn: m16.updateContact as any, signature: "values: ContactFormValues,", params: [{"name":"values","type":"ContactFormValues","optional":false}], doc: "", schemas: {  } },
  "contact.deleteContactById": { fn: m16.deleteContactById as any, signature: "contactId: string,", params: [{"name":"contactId","type":"string","optional":false}], doc: "", schemas: {  } },
  "contact.getContactList": { fn: m17.getContactList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, search?: string, roleId?: string,", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"search","type":"string","optional":true},{"name":"roleId","type":"string","optional":true}], doc: "Contacts get their own query rather than getReferenceEntityList: that helper counts jobs grouped by an FK on Job, and a contact reaches Job only through JobContact. The role filter has no equivalent there either.", schemas: {  } },
  "contact.getAllContacts": { fn: m17.getAllContacts as any, signature: "", params: [], doc: "The job-tab picker filters a preloaded array, so `value` carries everything worth searching on — name, email and employer.", schemas: {  } },
  "contact.getContactById": { fn: m17.getContactById as any, signature: "contactId: string,", params: [{"name":"contactId","type":"string","optional":false}], doc: "", schemas: {  } },
  "contactRole.getAllContactRoles": { fn: m18.getAllContactRoles as any, signature: "", params: [], doc: "", schemas: {  } },
  "contactRole.getContactRoleList": { fn: m18.getContactRoleList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, search?: string,", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"search","type":"string","optional":true}], doc: "Not getReferenceEntityList: that helper counts jobs grouped by an FK on Job, and a role reaches Job only through JobContact.", schemas: {  } },
  "contactRole.createContactRole": { fn: m18.createContactRole as any, signature: "label: string,", params: [{"name":"label","type":"string","optional":false}], doc: "", schemas: {  } },
  "contactRole.deleteContactRoleById": { fn: m18.deleteContactRoleById as any, signature: "roleId: string,", params: [{"name":"roleId","type":"string","optional":false}], doc: "", schemas: {  } },
  "coverLetter.getCoverLetterList": { fn: m19.getCoverLetterList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true}], doc: "", schemas: {  } },
  "coverLetter.createCoverLetter": { fn: m19.createCoverLetter as any, signature: "title: string, content: string", params: [{"name":"title","type":"string","optional":false},{"name":"content","type":"string","optional":false}], doc: "", schemas: {  } },
  "coverLetter.updateCoverLetter": { fn: m19.updateCoverLetter as any, signature: "id: string, title: string, content: string", params: [{"name":"id","type":"string","optional":false},{"name":"title","type":"string","optional":false},{"name":"content","type":"string","optional":false}], doc: "", schemas: {  } },
  "coverLetter.deleteCoverLetterById": { fn: m19.deleteCoverLetterById as any, signature: "coverLetterId: string", params: [{"name":"coverLetterId","type":"string","optional":false}], doc: "", schemas: {  } },
  "coverLetter.generateCoverLetterForJob": { fn: m19.generateCoverLetterForJob as any, signature: "jobId: string, markdown: string", params: [{"name":"jobId","type":"string","optional":false},{"name":"markdown","type":"string","optional":false}], doc: "", schemas: {  } },
  "job.addJob": { fn: m20.addJob as any, signature: "data: z.infer<typeof AddJobFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddJobFormSchema>","optional":false}], doc: "", schemas: { AddJobFormSchema } },
  "job.updateJob": { fn: m20.updateJob as any, signature: "data: z.infer<typeof AddJobFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddJobFormSchema>","optional":false}], doc: "", schemas: { AddJobFormSchema } },
  "job.deleteJobById": { fn: m20.deleteJobById as any, signature: "jobId: string,", params: [{"name":"jobId","type":"string","optional":false}], doc: "", schemas: {  } },
  "job.getJobsList": { fn: m21.getJobsList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, filter?: string, search?: string, companyValue?: string, appliedOnly?: boolean, titleValue?: string, locationValue?: string, sourceValue?: string, sort?: JobSort[],", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"filter","type":"string","optional":true},{"name":"search","type":"string","optional":true},{"name":"companyValue","type":"string","optional":true},{"name":"appliedOnly","type":"boolean","optional":true},{"name":"titleValue","type":"string","optional":true},{"name":"locationValue","type":"string","optional":true},{"name":"sourceValue","type":"string","optional":true},{"name":"sort","type":"JobSort[]","optional":true}], doc: "", schemas: {  } },
  "job.getJobDetails": { fn: m21.getJobDetails as any, signature: "jobId: string,", params: [{"name":"jobId","type":"string","optional":false}], doc: "", schemas: {  } },
  "job.getStatusList": { fn: m22.getStatusList as any, signature: "", params: [], doc: "JobStatus is global reference data with no createdBy column, so unlike every other list here it is not scoped to the current user.", schemas: {  } },
  "job.getJobSourceList": { fn: m22.getJobSourceList as any, signature: "", params: [], doc: "", schemas: {  } },
  "job.createLocation": { fn: m22.createLocation as any, signature: "label: string,", params: [{"name":"label","type":"string","optional":false}], doc: "", schemas: {  } },
  "job.createJobSource": { fn: m22.createJobSource as any, signature: "label: string,", params: [{"name":"label","type":"string","optional":false}], doc: "", schemas: {  } },
  "job.updateJobStatus": { fn: m23.updateJobStatus as any, signature: "jobId: string, status: JobStatus,", params: [{"name":"jobId","type":"string","optional":false},{"name":"status","type":"JobStatus","optional":false}], doc: "", schemas: {  } },
  "job.saveJobMatchResult": { fn: m23.saveJobMatchResult as any, signature: "jobId: string, matchScore: number, matchData: string,", params: [{"name":"jobId","type":"string","optional":false},{"name":"matchScore","type":"number","optional":false},{"name":"matchData","type":"string","optional":false}], doc: "", schemas: {  } },
  "jobLocation.getAllJobLocations": { fn: m24.getAllJobLocations as any, signature: "", params: [], doc: "", schemas: {  } },
  "jobLocation.getJobLocationsList": { fn: m24.getJobLocationsList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, countBy?: string, search?: string,", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"countBy","type":"string","optional":true},{"name":"search","type":"string","optional":true}], doc: "", schemas: {  } },
  "jobLocation.deleteJobLocationById": { fn: m24.deleteJobLocationById as any, signature: "locationId: string", params: [{"name":"locationId","type":"string","optional":false}], doc: "", schemas: {  } },
  "jobSource.getJobSourceList": { fn: m25.getJobSourceList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, countBy?: string, search?: string,", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"countBy","type":"string","optional":true},{"name":"search","type":"string","optional":true}], doc: "", schemas: {  } },
  "jobSource.deleteJobSourceById": { fn: m25.deleteJobSourceById as any, signature: "jobSourceId: string", params: [{"name":"jobSourceId","type":"string","optional":false}], doc: "", schemas: {  } },
  "jobtitle.getAllJobTitles": { fn: m26.getAllJobTitles as any, signature: "", params: [], doc: "", schemas: {  } },
  "jobtitle.getJobTitleList": { fn: m26.getJobTitleList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, countBy?: string, search?: string,", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"countBy","type":"string","optional":true},{"name":"search","type":"string","optional":true}], doc: "", schemas: {  } },
  "jobtitle.createJobTitle": { fn: m26.createJobTitle as any, signature: "label: string", params: [{"name":"label","type":"string","optional":false}], doc: "", schemas: {  } },
  "jobtitle.deleteJobTitleById": { fn: m26.deleteJobTitleById as any, signature: "jobTitleId: string", params: [{"name":"jobTitleId","type":"string","optional":false}], doc: "", schemas: {  } },
  "mcpToken.listMcpTokens": { fn: m27.listMcpTokens as any, signature: "", params: [], doc: "", schemas: {  } },
  "mcpToken.revokeMcpToken": { fn: m27.revokeMcpToken as any, signature: "id: string", params: [{"name":"id","type":"string","optional":false}], doc: "", schemas: {  } },
  "note.getNotesByJobId": { fn: m28.getNotesByJobId as any, signature: "jobId: string", params: [{"name":"jobId","type":"string","optional":false}], doc: "", schemas: {  } },
  "note.addNote": { fn: m28.addNote as any, signature: "data: z.infer<typeof NoteFormSchema>", params: [{"name":"data","type":"z.infer<typeof NoteFormSchema>","optional":false}], doc: "", schemas: { NoteFormSchema } },
  "note.updateNote": { fn: m28.updateNote as any, signature: "data: z.infer<typeof NoteFormSchema>", params: [{"name":"data","type":"z.infer<typeof NoteFormSchema>","optional":false}], doc: "", schemas: { NoteFormSchema } },
  "note.deleteNote": { fn: m28.deleteNote as any, signature: "noteId: string", params: [{"name":"noteId","type":"string","optional":false}], doc: "", schemas: {  } },
  "profile.addCertification": { fn: m29.addCertification as any, signature: "data: z.infer<typeof AddCertificationFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddCertificationFormSchema>","optional":false}], doc: "", schemas: { AddCertificationFormSchema } },
  "profile.updateCertification": { fn: m29.updateCertification as any, signature: "data: z.infer<typeof AddCertificationFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddCertificationFormSchema>","optional":false}], doc: "", schemas: { AddCertificationFormSchema } },
  "profile.addContactInfo": { fn: m30.addContactInfo as any, signature: "data: z.infer<typeof AddContactInfoFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddContactInfoFormSchema>","optional":false}], doc: "", schemas: { AddContactInfoFormSchema } },
  "profile.updateContactInfo": { fn: m30.updateContactInfo as any, signature: "data: z.infer<typeof AddContactInfoFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddContactInfoFormSchema>","optional":false}], doc: "", schemas: { AddContactInfoFormSchema } },
  "profile.getDefaultContactInfo": { fn: m30.getDefaultContactInfo as any, signature: "", params: [], doc: "Returns a bare value rather than a result envelope, matching the shape of getDefaultResumeId next door. Null means \"no letterhead\" — the letter then degrades to date + body. getCurrentUser, not this module's usual requireUser: \"no session\" has to return null like every other no-letterhead case, not ", schemas: {  } },
  "profile.getDefaultResumeId": { fn: m31.getDefaultResumeId as any, signature: "", params: [], doc: "", schemas: {  } },
  "profile.setDefaultResume": { fn: m31.setDefaultResume as any, signature: "resumeId: string,", params: [{"name":"resumeId","type":"string","optional":false}], doc: "", schemas: {  } },
  "profile.addEducation": { fn: m32.addEducation as any, signature: "data: z.infer<typeof AddEducationFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddEducationFormSchema>","optional":false}], doc: "", schemas: { AddEducationFormSchema } },
  "profile.updateEducation": { fn: m32.updateEducation as any, signature: "data: z.infer<typeof AddEducationFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddEducationFormSchema>","optional":false}], doc: "", schemas: { AddEducationFormSchema } },
  "profile.addExperience": { fn: m33.addExperience as any, signature: "data: z.infer<typeof AddExperienceFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddExperienceFormSchema>","optional":false}], doc: "", schemas: { AddExperienceFormSchema } },
  "profile.updateExperience": { fn: m33.updateExperience as any, signature: "data: z.infer<typeof AddExperienceFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddExperienceFormSchema>","optional":false}], doc: "", schemas: { AddExperienceFormSchema } },
  "profile.deleteFile": { fn: m34.deleteFile as any, signature: "fileId: string", params: [{"name":"fileId","type":"string","optional":false}], doc: "", schemas: {  } },
  "profile.getResumeList": { fn: m35.getResumeList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, minSections: number = 0,", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"minSections","type":"number","optional":true}], doc: "", schemas: {  } },
  "profile.getResumeById": { fn: m35.getResumeById as any, signature: "resumeId: string,", params: [{"name":"resumeId","type":"string","optional":false}], doc: "", schemas: {  } },
  "profile.saveResumeReviewResult": { fn: m35.saveResumeReviewResult as any, signature: "resumeId: string, reviewData: string,", params: [{"name":"resumeId","type":"string","optional":false},{"name":"reviewData","type":"string","optional":false}], doc: "", schemas: {  } },
  "profile.createResumeProfile": { fn: m35.createResumeProfile as any, signature: "title: string,", params: [{"name":"title","type":"string","optional":false}], doc: "No file here: a create with a file goes through the upload route only", schemas: {  } },
  "profile.editResume": { fn: m35.editResume as any, signature: "id: string, title: string,", params: [{"name":"id","type":"string","optional":false},{"name":"title","type":"string","optional":false}], doc: "Title only: the file is replaced through the upload route, never from here", schemas: {  } },
  "profile.deleteResumeById": { fn: m35.deleteResumeById as any, signature: "resumeId: string,", params: [{"name":"resumeId","type":"string","optional":false}], doc: "", schemas: {  } },
  "profile.getResumeCopyTitleSuggestion": { fn: m36.getResumeCopyTitleSuggestion as any, signature: "resumeId: string,", params: [{"name":"resumeId","type":"string","optional":false}], doc: "", schemas: {  } },
  "profile.copyResume": { fn: m36.copyResume as any, signature: "resumeId: string, title: string,", params: [{"name":"resumeId","type":"string","optional":false},{"name":"title","type":"string","optional":false}], doc: "", schemas: {  } },
  "profile.addSkillsSection": { fn: m37.addSkillsSection as any, signature: "data: z.infer<typeof AddSkillsFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddSkillsFormSchema>","optional":false}], doc: "", schemas: { AddSkillsFormSchema } },
  "profile.updateSkillsSection": { fn: m37.updateSkillsSection as any, signature: "data: z.infer<typeof UpdateSkillsFormSchema>,", params: [{"name":"data","type":"z.infer<typeof UpdateSkillsFormSchema>","optional":false}], doc: "", schemas: { UpdateSkillsFormSchema } },
  "profile.deleteSkillsSection": { fn: m37.deleteSkillsSection as any, signature: "sectionId: string,", params: [{"name":"sectionId","type":"string","optional":false}], doc: "", schemas: {  } },
  "profile.addResumeSummary": { fn: m38.addResumeSummary as any, signature: "data: z.infer<typeof AddSummarySectionFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddSummarySectionFormSchema>","optional":false}], doc: "", schemas: { AddSummarySectionFormSchema } },
  "profile.updateResumeSummary": { fn: m38.updateResumeSummary as any, signature: "data: z.infer<typeof AddSummarySectionFormSchema>,", params: [{"name":"data","type":"z.infer<typeof AddSummarySectionFormSchema>","optional":false}], doc: "", schemas: { AddSummarySectionFormSchema } },
  "question.getQuestionsList": { fn: m39.getQuestionsList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, filter?: string, search?: string", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"filter","type":"string","optional":true},{"name":"search","type":"string","optional":true}], doc: "", schemas: {  } },
  "question.getQuestionById": { fn: m39.getQuestionById as any, signature: "questionId: string", params: [{"name":"questionId","type":"string","optional":false}], doc: "", schemas: {  } },
  "question.createQuestion": { fn: m39.createQuestion as any, signature: "data: z.infer<typeof AddQuestionFormSchema>", params: [{"name":"data","type":"z.infer<typeof AddQuestionFormSchema>","optional":false}], doc: "", schemas: { AddQuestionFormSchema } },
  "question.updateQuestion": { fn: m39.updateQuestion as any, signature: "data: z.infer<typeof AddQuestionFormSchema>", params: [{"name":"data","type":"z.infer<typeof AddQuestionFormSchema>","optional":false}], doc: "", schemas: { AddQuestionFormSchema } },
  "question.deleteQuestion": { fn: m39.deleteQuestion as any, signature: "questionId: string", params: [{"name":"questionId","type":"string","optional":false}], doc: "", schemas: {  } },
  "question.getTagsWithQuestionCounts": { fn: m39.getTagsWithQuestionCounts as any, signature: "", params: [], doc: "", schemas: {  } },
  "resumeImport.resolveImportCard": { fn: m40.resolveImportCard as any, signature: "resumeId: string, card: ImportCardPayload,", params: [{"name":"resumeId","type":"string","optional":false},{"name":"card","type":"ImportCardPayload","optional":false}], doc: "", schemas: {  } },
  "tag.getAllTags": { fn: m41.getAllTags as any, signature: "", params: [], doc: "", schemas: {  } },
  "tag.getTagList": { fn: m41.getTagList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, search?: string,", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"search","type":"string","optional":true}], doc: "", schemas: {  } },
  "tag.createTag": { fn: m41.createTag as any, signature: "label: string", params: [{"name":"label","type":"string","optional":false}], doc: "", schemas: {  } },
  "tag.deleteTagById": { fn: m41.deleteTagById as any, signature: "tagId: string,", params: [{"name":"tagId","type":"string","optional":false}], doc: "", schemas: {  } },
  "task.startActivityFromTask": { fn: m42.startActivityFromTask as any, signature: "taskId: string", params: [{"name":"taskId","type":"string","optional":false}], doc: "", schemas: {  } },
  "task.createTask": { fn: m43.createTask as any, signature: "data: z.infer<typeof AddTaskFormSchema>", params: [{"name":"data","type":"z.infer<typeof AddTaskFormSchema>","optional":false}], doc: "", schemas: { AddTaskFormSchema } },
  "task.updateTask": { fn: m43.updateTask as any, signature: "data: z.infer<typeof AddTaskFormSchema>", params: [{"name":"data","type":"z.infer<typeof AddTaskFormSchema>","optional":false}], doc: "", schemas: { AddTaskFormSchema } },
  "task.updateTaskStatus": { fn: m43.updateTaskStatus as any, signature: "taskId: string, status: TaskStatus", params: [{"name":"taskId","type":"string","optional":false},{"name":"status","type":"TaskStatus","optional":false}], doc: "", schemas: {  } },
  "task.deleteTaskById": { fn: m43.deleteTaskById as any, signature: "taskId: string", params: [{"name":"taskId","type":"string","optional":false}], doc: "", schemas: {  } },
  "task.getTasksList": { fn: m44.getTasksList as any, signature: "page: number = 1, limit: number = APP_CONSTANTS.RECORDS_PER_PAGE, filter?: string, statusFilter?: TaskStatus[], search?: string, groupBy?: TaskGroupBy", params: [{"name":"page","type":"number","optional":true},{"name":"limit","type":"number","optional":true},{"name":"filter","type":"string","optional":true},{"name":"statusFilter","type":"TaskStatus[]","optional":true},{"name":"search","type":"string","optional":true},{"name":"groupBy","type":"TaskGroupBy","optional":true}], doc: "", schemas: {  } },
  "task.getTaskById": { fn: m44.getTaskById as any, signature: "taskId: string", params: [{"name":"taskId","type":"string","optional":false}], doc: "", schemas: {  } },
  "task.getActivityTypesWithTaskCounts": { fn: m44.getActivityTypesWithTaskCounts as any, signature: "", params: [], doc: "", schemas: {  } },
  "userSettings.getUserSettings": { fn: m45.getUserSettings as any, signature: "", params: [], doc: "", schemas: {  } },
  "userSettings.updateUserSettings": { fn: m45.updateUserSettings as any, signature: "settings: Partial<UserSettingsData>", params: [{"name":"settings","type":"Partial<UserSettingsData>","optional":false}], doc: "", schemas: {  } },
  "userSettings.updateAiSettings": { fn: m45.updateAiSettings as any, signature: "aiSettings: AiSettings", params: [{"name":"aiSettings","type":"AiSettings","optional":false}], doc: "", schemas: {  } },
  "userSettings.updateDisplaySettings": { fn: m45.updateDisplaySettings as any, signature: "displaySettings: DisplaySettings", params: [{"name":"displaySettings","type":"DisplaySettings","optional":false}], doc: "", schemas: {  } },
};
